#!/bin/bash

# Production Deployment Checklist for Rupomoti.com

echo "🚀 PRODUCTION DEPLOYMENT CHECKLIST"
echo "=================================="
echo ""

echo "✅ 1. Google OAuth Settings"
echo "   - Authorized JavaScript origins: ✅ Set"
echo "   - Authorized redirect URIs: ✅ Set"
echo "   - Development: http://localhost:3000/api/auth/callback/google"
echo "   - Production: https://rupomoti.com/api/auth/callback/google"
echo "   - Vercel: https://rupomoti.vercel.app/api/auth/callback/google"
echo ""

echo "✅ 2. Local Environment File"
echo "   - .env.production file: ✅ Updated"
echo "   - NEXTAUTH_URL: https://rupomoti.com"
echo ""

echo "🔍 3. NEXT STEPS - Verify Vercel Environment Variables"
echo "   Go to: https://vercel.com/dashboard"
echo "   1. Select your 'rupomoti' project"
echo "   2. Go to Settings → Environment Variables"
echo "   3. Ensure these are set for PRODUCTION:"
echo ""
echo "   Required Variables:"
echo "   ==================="
echo "   DATABASE_URL = mongodb+srv://rupomotibusiness:pGhePonAlcVB3sf0@cluster0.p0tpuuo.mongodb.net/rupomoti?retryWrites=true&w=majority"
echo "   NEXTAUTH_URL = https://rupomoti.com"
echo "   NEXTAUTH_SECRET = Q7z9f8mHBKwP6R2VjpThcFMsYAYa5nKM"
echo "   GOOGLE_CLIENT_ID = 340102371641-uj74n18rrpbql3g8r6vqg2v5ha94mm9u.apps.googleusercontent.com"
echo "   GOOGLE_CLIENT_SECRET = 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"
echo "   NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = dotinshdj"
echo "   NEXT_PUBLIC_CLOUDINARY_API_KEY = 258755974622473"
echo "   NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET = rupomoti_uploads"
echo "   NODE_ENV = production"
echo ""

echo "🚀 4. DEPLOY AND TEST"
echo "   1. After setting environment variables, click 'Redeploy' in Vercel"
echo "   2. Wait for deployment to complete"
echo "   3. Test these URLs:"
echo "      - https://rupomoti.com (homepage - should show products)"
echo "      - https://rupomoti.com/shop (should show products, not 'No Products Found')"
echo "      - https://rupomoti.com/new-arrivals (should work without errors)"
echo "      - Sign in with Google (should work without redirect errors)"
echo ""

echo "📋 5. VERIFICATION COMMANDS"
echo "   Open browser console on https://rupomoti.com and run:"
echo "   -------------------------------------------------------"
echo "   fetch('/api/products-mongo?limit=3').then(r=>r.json()).then(console.log)"
echo "   fetch('/api/categories').then(r=>r.json()).then(console.log)"
echo ""

echo "🎯 Expected Results After Fix:"
echo "   - Homepage: Categories and products visible"
echo "   - Shop page: Products load correctly"
echo "   - New arrivals: Page loads without errors"
echo "   - Google sign-in: Works without redirect errors"
echo "   - All authentication: Functions properly"
echo ""

echo "🆘 If Still Not Working:"
echo "   1. Check Vercel deployment logs for errors"
echo "   2. Verify environment variables are saved correctly"
echo "   3. Clear browser cache and cookies"
echo "   4. Try incognito/private browsing mode"
echo "   5. Check browser console for JavaScript errors"
