export const BANGLADESH_DIVISIONS = [
    { id: '1', name: 'Barishal' },
    { id: '2', name: 'Chattogram' },
    { id: '3', name: 'Dhaka' },
    { id: '4', name: 'Khulna' },
    { id: '5', name: 'Rajshahi' },
    { id: '6', name: 'Rangpur' },
    { id: '7', name: 'Sylhet' },
    { id: '8', name: 'Mymensingh' },
  ];
  
  export const BANGLADESH_DISTRICTS: { [key: string]: { id: string, name: string }[] } = {
    '1': [
      { id: '34', name: 'Barguna' },
      { id: '35', name: 'Barishal' },
      { id: '36', name: 'Bhola' },
      { id: '37', name: 'Jhalokati' },
      { id: '38', name: 'Patuakhali' },
      { id: '39', name: 'Pirojpur' },
    ],
    '2': [
      { id: '40', name: 'Bandarban' },
      { id: '41', name: 'Brahmanbaria' },
      { id: '42', name: 'Chandpur' },
      { id: '43', name: 'Chattogram' },
      { id: '44', name: 'Cumilla' },
      { id: '45', name: 'Cox\'s Bazar' },
      { id: '46', name: 'Feni' },
      { id: '47', name: 'Khagrachari' },
      { id: '48', name: 'Lakshmipur' },
      { id: '49', name: 'Noakhali' },
      { id: '50', name: 'Rangamati' },
    ],
    '3': [
      { id: '1', name: 'Dhaka' },
      { id: '2', name: 'Faridpur' },
      { id: '3', name: 'Gazipur' },
      { id: '4', name: 'Gopalganj' },
      { id: '6', name: 'Kishoreganj' },
      { id: '7', name: 'Madaripur' },
      { id: '8', name: 'Manikganj' },
      { id: '9', name: 'Munshiganj' },
      { id: '11', name: 'Narayanganj' },
      { id: '12', name: 'Narsingdi' },
      { id: '14', name: 'Rajbari' },
      { id: '15', name: 'Shariatpur' },
      { id: '17', name: 'Tangail' },
    ],
    '4': [
      { id: '55', name: 'Bagerhat' },
      { id: '56', name: 'Chuadanga' },
      { id: '57', name: 'Jashore' },
      { id: '58', name: 'Jhenaidah' },
      { id: '59', name: 'Khulna' },
      { id: '60', name: 'Kushtia' },
      { id: '61', name: 'Magura' },
      { id: '62', name: 'Meherpur' },
      { id: '63', name: 'Narail' },
      { id: '64', name: 'Satkhira' },
    ],
    '5': [
      { id: '18', name: 'Bogura' },
      { id: '19', name: 'Joypurhat' },
      { id: '20', name: 'Naogaon' },
      { id: '21', name: 'Natore' },
      { id: '22', name: 'Nawabganj' },
      { id: '23', name: 'Pabna' },
      { id: '24', name: 'Rajshahi' },
      { id: '25', name: 'Sirajgonj' },
    ],
    '6': [
      { id: '26', name: 'Dinajpur' },
      { id: '27', name: 'Gaibandha' },
      { id: '28', name: 'Kurigram' },
      { id: '29', name: 'Lalmonirhat' },
      { id: '30', name: 'Nilphamari' },
      { id: '31', name: 'Panchagarh' },
      { id: '32', name: 'Rangpur' },
      { id: '33', name: 'Thakurgaon' },
    ],
    '7': [
      { id: '51', name: 'Habiganj' },
      { id: '52', name: 'Maulvibazar' },
      { id: '53', name: 'Sunamganj' },
      { id: '54', name: 'Sylhet' },
    ],
    '8': [
      { id: '5', name: 'Jamalpur' },
      { id: '10', name: 'Mymensingh' },
      { id: '13', name: 'Netrokona' },
      { id: '16', name: 'Sherpur' },
    ],
  };
  
  export const BANGLADESH_UPAZILAS: { [key: string]: { id: string, name: string }[] } = {
    '1': [
      { id: '145', name: 'Dhamrai' },
      { id: '146', name: 'Dohar' },
      { id: '147', name: 'Keraniganj' },
      { id: '148', name: 'Nawabganj' },
      { id: '149', name: 'Savar' },
    ],
    '2': [
      { id: '150', name: 'Faridpur Sadar' },
      { id: '151', name: 'Boalmari' },
      { id: '152', name: 'Alfadanga' },
      { id: '153', name: 'Madhukhali' },
      { id: '154', name: 'Bhanga' },
      { id: '155', name: 'Nagarkanda' },
      { id: '156', name: 'Charbhadrasan' },
      { id: '157', name: 'Sadarpur' },
      { id: '158', name: 'Shaltha' },
    ],
    '3': [
      { id: '159', name: 'Gazipur Sadar-Joydebpur' },
      { id: '160', name: 'Kaliakior' },
      { id: '161', name: 'Kapasia' },
      { id: '162', name: 'Sripur' },
      { id: '163', name: 'Kaliganj' },
      { id: '164', name: 'Tongi' },
    ],
    '4': [
      { id: '165', name: 'Gopalganj Sadar' },
      { id: '166', name: 'Kashiani' },
      { id: '167', name: 'Kotalipara' },
      { id: '168', name: 'Muksudpur' },
      { id: '169', name: 'Tungipara' },
    ],
    '5': [
      { id: '170', name: 'Dewanganj' },
      { id: '171', name: 'Baksiganj' },
      { id: '172', name: 'Islampur' },
      { id: '173', name: 'Jamalpur Sadar' },
      { id: '174', name: 'Madarganj' },
      { id: '175', name: 'Melandaha' },
      { id: '176', name: 'Sarishabari' },
      { id: '177', name: 'Narundi Police I.C' },
    ],
    '6': [
      { id: '178', name: 'Astagram' },
      { id: '179', name: 'Bajitpur' },
      { id: '180', name: 'Bhairab' },
      { id: '181', name: 'Hossainpur' },
      { id: '182', name: 'Itna' },
      { id: '183', name: 'Karimganj' },
      { id: '184', name: 'Katiadi' },
      { id: '185', name: 'Kishoreganj Sadar' },
      { id: '186', name: 'Kuliarchar' },
      { id: '187', name: 'Mithamain' },
      { id: '188', name: 'Nikli' },
      { id: '189', name: 'Pakundia' },
      { id: '190', name: 'Tarail' },
    ],
    '7': [
      { id: '191', name: 'Madaripur Sadar' },
      { id: '192', name: 'Kalkini' },
      { id: '193', name: 'Rajoir' },
      { id: '194', name: 'Shibchar' },
      { id: '495', name: 'Dasar' },
    ],
    '8': [
      { id: '195', name: 'Manikganj Sadar' },
      { id: '196', name: 'Singair' },
      { id: '197', name: 'Shibalaya' },
      { id: '198', name: 'Saturia' },
      { id: '199', name: 'Harirampur' },
      { id: '200', name: 'Ghior' },
      { id: '201', name: 'Daulatpur' },
    ],
    '9': [
      { id: '202', name: 'Lohajang' },
      { id: '203', name: 'Sreenagar' },
      { id: '204', name: 'Munshiganj Sadar' },
      { id: '205', name: 'Sirajdikhan' },
      { id: '206', name: 'Tongibari' },
      { id: '207', name: 'Gazaria' },
    ],
    '10': [
      { id: '208', name: 'Bhaluka' },
      { id: '209', name: 'Trishal' },
      { id: '210', name: 'Haluaghat' },
      { id: '211', name: 'Muktagachha' },
      { id: '212', name: 'Dhobaura' },
      { id: '213', name: 'Fulbaria' },
      { id: '214', name: 'Gaffargaon' },
      { id: '215', name: 'Gauripur' },
      { id: '216', name: 'Ishwarganj' },
      { id: '217', name: 'Mymensingh Sadar' },
      { id: '218', name: 'Nandail' },
      { id: '219', name: 'Phulpur' },
    ],
    '11': [
      { id: '220', name: 'Araihazar' },
      { id: '221', name: 'Sonargaon' },
      { id: '222', name: 'Bandar' },
      { id: '223', name: 'Naryanganj Sadar' },
      { id: '224', name: 'Rupganj' },
      { id: '225', name: 'Siddirgonj' },
    ],
    '12': [
      { id: '226', name: 'Belabo' },
      { id: '227', name: 'Monohardi' },
      { id: '228', name: 'Narsingdi Sadar' },
      { id: '229', name: 'Palash' },
      { id: '230', name: 'Raipura, Narsingdi' },
      { id: '231', name: 'Shibpur' },
    ],
    '13': [
      { id: '232', name: 'Kendua Upazilla' },
      { id: '233', name: 'Atpara Upazilla' },
      { id: '234', name: 'Barhatta Upazilla' },
      { id: '235', name: 'Durgapur Upazilla' },
      { id: '236', name: 'Kalmakanda Upazilla' },
      { id: '237', name: 'Madan Upazilla' },
      { id: '238', name: 'Mohanganj Upazilla' },
      { id: '239', name: 'Netrakona-S Upazilla' },
      { id: '240', name: 'Purbadhala Upazilla' },
      { id: '241', name: 'Khaliajuri Upazilla' },
    ],
    '14': [
      { id: '242', name: 'Baliakandi' },
      { id: '243', name: 'Goalandaghat' },
      { id: '244', name: 'Pangsha' },
      { id: '245', name: 'Kalukhali' },
      { id: '246', name: 'Rajbari Sadar' },
    ],
    '15': [
      { id: '247', name: 'Shariatpur Sadar -Palong' },
      { id: '248', name: 'Damudya' },
      { id: '249', name: 'Naria' },
      { id: '250', name: 'Jajira' },
      { id: '251', name: 'Bhedarganj' },
      { id: '252', name: 'Gosairhat' },
    ],
    '16': [
      { id: '253', name: 'Jhenaigati' },
      { id: '254', name: 'Nakla' },
      { id: '255', name: 'Nalitabari' },
      { id: '256', name: 'Sherpur Sadar' },
      { id: '257', name: 'Sreebardi' },
    ],
    '17': [
      { id: '258', name: 'Tangail Sadar' },
      { id: '259', name: 'Sakhipur' },
      { id: '260', name: 'Basail' },
      { id: '261', name: 'Madhupur' },
      { id: '262', name: 'Ghatail' },
      { id: '263', name: 'Kalihati' },
      { id: '264', name: 'Nagarpur' },
      { id: '265', name: 'Mirzapur' },
      { id: '266', name: 'Gopalpur' },
      { id: '267', name: 'Delduar' },
      { id: '268', name: 'Bhuapur' },
      { id: '269', name: 'Dhanbari' },
    ],
    '18': [
      { id: '329', name: 'Adamdighi' },
      { id: '330', name: 'Bogra Sadar' },
      { id: '331', name: 'Sherpur' },
      { id: '332', name: 'Dhunat' },
      { id: '333', name: 'Dhupchanchia' },
      { id: '334', name: 'Gabtali' },
      { id: '335', name: 'Kahaloo' },
      { id: '336', name: 'Nandigram' },
      { id: '337', name: 'Sahajanpur' },
      { id: '338', name: 'Sariakandi' },
      { id: '339', name: 'Shibganj' },
      { id: '340', name: 'Sonatala' },
    ],
    '19': [
      { id: '341', name: 'Joypurhat S' },
      { id: '342', name: 'Akkelpur' },
      { id: '343', name: 'Kalai' },
      { id: '344', name: 'Khetlal' },
      { id: '345', name: 'Panchbibi' },
    ],
    '20': [
      { id: '346', name: 'Naogaon Sadar' },
      { id: '347', name: 'Mohadevpur' },
      { id: '348', name: 'Manda' },
      { id: '349', name: 'Niamatpur' },
      { id: '350', name: 'Atrai' },
      { id: '351', name: 'Raninagar' },
      { id: '352', name: 'Patnitala' },
      { id: '353', name: 'Dhamoirhat' },
      { id: '354', name: 'Sapahar' },
      { id: '355', name: 'Porsha' },
      { id: '356', name: 'Badalgachhi' },
    ],
    '21': [
      { id: '357', name: 'Natore Sadar' },
      { id: '358', name: 'Baraigram' },
      { id: '359', name: 'Bagatipara' },
      { id: '360', name: 'Lalpur' },
      { id: '361', name: 'Natore Sadar' },
      { id: '362', name: 'Baraigram' },
    ],
    '22': [
      { id: '363', name: 'Bholahat' },
      { id: '364', name: 'Gomastapur' },
      { id: '365', name: 'Nachole' },
      { id: '366', name: 'Nawabganj Sadar' },
      { id: '367', name: 'Shibganj' },
    ],
    '23': [
      { id: '368', name: 'Atgharia' },
      { id: '369', name: 'Bera' },
      { id: '370', name: 'Bhangura' },
      { id: '371', name: 'Chatmohar' },
      { id: '372', name: 'Faridpur' },
      { id: '373', name: 'Ishwardi' },
      { id: '374', name: 'Pabna Sadar' },
      { id: '375', name: 'Santhia' },
      { id: '376', name: 'Sujanagar' },
    ],
    '24': [
      { id: '377', name: 'Bagha' },
      { id: '378', name: 'Bagmara' },
      { id: '379', name: 'Charghat' },
      { id: '380', name: 'Durgapur' },
      { id: '381', name: 'Godagari' },
      { id: '382', name: 'Mohanpur' },
      { id: '383', name: 'Paba' },
      { id: '384', name: 'Puthia' },
      { id: '385', name: 'Tanore' },
    ],
    '25': [
      { id: '386', name: 'Sirajganj Sadar' },
      { id: '387', name: 'Belkuchi' },
      { id: '388', name: 'Chauhali' },
      { id: '389', name: 'Kamarkhanda' },
      { id: '390', name: 'Kazipur' },
      { id: '391', name: 'Raiganj' },
      { id: '392', name: 'Shahjadpur' },
      { id: '393', name: 'Tarash' },
      { id: '394', name: 'Ullahpara' },
    ],
    '26': [
      { id: '395', name: 'Birampur' },
      { id: '396', name: 'Birganj' },
      { id: '397', name: 'Biral' },
      { id: '398', name: 'Bochaganj' },
      { id: '399', name: 'Chirirbandar' },
      { id: '400', name: 'Phulbari' },
      { id: '401', name: 'Ghoraghat' },
      { id: '402', name: 'Hakimpur' },
      { id: '403', name: 'Kaharole' },
      { id: '404', name: 'Khansama' },
      { id: '405', name: 'Dinajpur Sadar' },
      { id: '406', name: 'Nawabganj' },
      { id: '407', name: 'Parbatipur' },
    ],
    '27': [
      { id: '408', name: 'Fulchhari' },
      { id: '409', name: 'Gaibandha sadar' },
      { id: '410', name: 'Gobindaganj' },
      { id: '411', name: 'Palashbari' },
      { id: '412', name: 'Sadullapur' },
      { id: '413', name: 'Saghata' },
      { id: '414', name: 'Sundarganj' },
    ],
    '28': [
      { id: '415', name: 'Kurigram Sadar' },
      { id: '416', name: 'Nageshwari' },
      { id: '417', name: 'Bhurungamari' },
      { id: '418', name: 'Phulbari' },
      { id: '419', name: 'Rajarhat' },
      { id: '420', name: 'Ulipur' },
      { id: '421', name: 'Chilmari' },
      { id: '422', name: 'Rowmari' },
      { id: '423', name: 'Char Rajibpur' },
    ],
    '29': [
      { id: '424', name: 'Lalmanirhat Sadar' },
      { id: '425', name: 'Aditmari' },
      { id: '426', name: 'Kaliganj' },
      { id: '427', name: 'Hatibandha' },
      { id: '428', name: 'Patgram' },
    ],
    '30': [
      { id: '429', name: 'Nilphamari Sadar' },
      { id: '430', name: 'Saidpur' },
      { id: '431', name: 'Jaldhaka' },
      { id: '432', name: 'Kishoreganj' },
      { id: '433', name: 'Domar' },
      { id: '434', name: 'Dimla' },
    ],
    '31': [
      { id: '435', name: 'Panchagarh Sadar' },
      { id: '436', name: 'Debiganj' },
      { id: '437', name: 'Boda' },
      { id: '438', name: 'Atwari' },
      { id: '439', name: 'Tetulia' },
    ],
    '32': [
      { id: '440', name: 'Badarganj' },
      { id: '441', name: 'Mithapukur' },
      { id: '442', name: 'Gangachara' },
      { id: '443', name: 'Kaunia' },
      { id: '444', name: 'Rangpur Sadar' },
      { id: '445', name: 'Pirgachha' },
      { id: '446', name: 'Pirganj' },
      { id: '447', name: 'Taraganj' },
    ],
    '33': [
      { id: '448', name: 'Thakurgaon Sadar' },
      { id: '449', name: 'Pirganj' },
      { id: '450', name: 'Baliadangi' },
      { id: '451', name: 'Haripur' },
      { id: '452', name: 'Ranisankail' },
    ],
    '34': [
      { id: '1', name: 'Amtali' },
      { id: '2', name: 'Bamna' },
      { id: '3', name: 'Barguna Sadar' },
      { id: '4', name: 'Betagi' },
      { id: '5', name: 'Patharghata' },
      { id: '6', name: 'Taltali' },
    ],
    '35': [
      { id: '7', name: 'Muladi' },
      { id: '8', name: 'Babuganj' },
      { id: '9', name: 'Agailjhara' },
      { id: '10', name: 'Barisal Sadar' },
      { id: '11', name: 'Bakerganj' },
      { id: '12', name: 'Banaripara' },
      { id: '13', name: 'Gaurnadi' },
      { id: '14', name: 'Hizla' },
      { id: '15', name: 'Mehendiganj' },
      { id: '16', name: 'Wazirpur' },
    ],
    '36': [
      { id: '17', name: 'Bhola Sadar' },
      { id: '18', name: 'Burhanuddin' },
      { id: '19', name: 'Char Fasson' },
      { id: '20', name: 'Daulatkhan' },
      { id: '21', name: 'Lalmohan' },
      { id: '22', name: 'Manpura' },
      { id: '23', name: 'Tazumuddin' },
    ],
    '37': [
      { id: '24', name: 'Jhalokati Sadar' },
      { id: '25', name: 'Kathalia' },
      { id: '26', name: 'Nalchity' },
      { id: '27', name: 'Rajapur' },
    ],
    '38': [
      { id: '28', name: 'Bauphal' },
      { id: '29', name: 'Dashmina' },
      { id: '30', name: 'Galachipa' },
      { id: '31', name: 'Kalapara' },
      { id: '32', name: 'Mirzaganj' },
      { id: '33', name: 'Patuakhali Sadar' },
      { id: '34', name: 'Dumki' },
      { id: '35', name: 'Rangabali' },
    ],
    '39': [
      { id: '36', name: 'Bhandaria' },
      { id: '37', name: 'Kaukhali' },
      { id: '38', name: 'Mathbaria' },
      { id: '39', name: 'Nazirpur' },
      { id: '40', name: 'Nesarabad' },
      { id: '41', name: 'Pirojpur Sadar' },
      { id: '42', name: 'Zianagar' },
    ],
    '40': [
      { id: '43', name: 'Bandarban Sadar' },
      { id: '44', name: 'Thanchi' },
      { id: '45', name: 'Lama' },
      { id: '46', name: 'Naikhongchhari' },
      { id: '47', name: 'Ali kadam' },
      { id: '48', name: 'Rowangchhari' },
      { id: '49', name: 'Ruma' },
    ],
    '41': [
      { id: '50', name: 'Brahmanbaria Sadar' },
      { id: '51', name: 'Ashuganj' },
      { id: '52', name: 'Nasirnagar' },
      { id: '53', name: 'Nabinagar' },
      { id: '54', name: 'Sarail' },
      { id: '55', name: 'Shahbazpur Town' },
      { id: '56', name: 'Kasba' },
      { id: '57', name: 'Akhaura' },
      { id: '58', name: 'Bancharampur' },
      { id: '59', name: 'Bijoynagar' },
    ],
    '42': [
      { id: '60', name: 'Chandpur Sadar' },
      { id: '61', name: 'Faridganj' },
      { id: '62', name: 'Haimchar' },
      { id: '63', name: 'Haziganj' },
      { id: '64', name: 'Kachua' },
      { id: '65', name: 'Matlab Uttar' },
      { id: '66', name: 'Matlab Dakkhin' },
      { id: '67', name: 'Shahrasti' },
    ],
    '43': [
      { id: '68', name: 'Anwara' },
      { id: '69', name: 'Banshkhali' },
      { id: '70', name: 'Boalkhali' },
      { id: '71', name: 'Chandanaish' },
      { id: '72', name: 'Fatikchhari' },
      { id: '73', name: 'Hathazari' },
      { id: '74', name: 'Lohagara' },
      { id: '75', name: 'Mirsharai' },
      { id: '76', name: 'Patiya' },
      { id: '77', name: 'Rangunia' },
      { id: '78', name: 'Raozan' },
      { id: '79', name: 'Sandwip' },
      { id: '80', name: 'Satkania' },
      { id: '81', name: 'Sitakunda' },
    ],
    '44': [
      { id: '82', name: 'Barura' },
      { id: '83', name: 'Brahmanpara' },
      { id: '84', name: 'Burichong' },
      { id: '85', name: 'Chandina' },
      { id: '86', name: 'Chauddagram' },
      { id: '87', name: 'Daudkandi' },
      { id: '88', name: 'Debidwar' },
      { id: '89', name: 'Homna' },
      { id: '90', name: 'Comilla Sadar' },
      { id: '91', name: 'Laksam' },
      { id: '92', name: 'Monohorgonj' },
      { id: '93', name: 'Meghna' },
      { id: '94', name: 'Muradnagar' },
      { id: '95', name: 'Nangalkot' },
      { id: '96', name: 'Comilla Sadar South' },
      { id: '97', name: 'Titas' },
    ],
    '45': [
      { id: '98', name: 'Chakaria' },
      { id: '100', name: '{{198}}\'\'{{199}}' },
      { id: '101', name: 'Kutubdia' },
      { id: '102', name: 'Maheshkhali' },
      { id: '103', name: 'Ramu' },
      { id: '104', name: 'Teknaf' },
      { id: '105', name: 'Ukhia' },
      { id: '106', name: 'Pekua' },
      { id: '493', name: 'Eidgaon' },
    ],
    '46': [
      { id: '107', name: 'Feni Sadar' },
      { id: '108', name: 'Chagalnaiya' },
      { id: '109', name: 'Daganbhyan' },
      { id: '110', name: 'Parshuram' },
      { id: '111', name: 'Fhulgazi' },
      { id: '112', name: 'Sonagazi' },
    ],
    '47': [
      { id: '113', name: 'Dighinala' },
      { id: '114', name: 'Khagrachhari' },
      { id: '115', name: 'Lakshmichhari' },
      { id: '116', name: 'Mahalchhari' },
      { id: '117', name: 'Manikchhari' },
      { id: '118', name: 'Matiranga' },
      { id: '119', name: 'Panchhari' },
      { id: '120', name: 'Ramgarh' },
    ],
    '48': [
      { id: '121', name: 'Lakshmipur Sadar' },
      { id: '122', name: 'Raipur' },
      { id: '123', name: 'Ramganj' },
      { id: '124', name: 'Ramgati' },
      { id: '125', name: 'Komol Nagar' },
    ],
    '49': [
      { id: '126', name: 'Noakhali Sadar' },
      { id: '127', name: 'Begumganj' },
      { id: '128', name: 'Chatkhil' },
      { id: '129', name: 'Companyganj' },
      { id: '130', name: 'Shenbag' },
      { id: '131', name: 'Hatia' },
      { id: '132', name: 'Kobirhat' },
      { id: '133', name: 'Sonaimuri' },
      { id: '134', name: 'Suborno Char' },
    ],
    '50': [
      { id: '135', name: 'Rangamati Sadar' },
      { id: '136', name: 'Belaichhari' },
      { id: '137', name: 'Bagaichhari' },
      { id: '138', name: 'Barkal' },
      { id: '139', name: 'Juraichhari' },
      { id: '140', name: 'Rajasthali' },
      { id: '141', name: 'Kaptai' },
      { id: '142', name: 'Langadu' },
      { id: '143', name: 'Nannerchar' },
      { id: '144', name: 'Kaukhali' },
    ],
    '51': [
      { id: '453', name: 'Ajmiriganj' },
      { id: '454', name: 'Baniachang' },
      { id: '455', name: 'Bahubal' },
      { id: '456', name: 'Chunarughat' },
      { id: '457', name: 'Habiganj Sadar' },
      { id: '458', name: 'Lakhai' },
      { id: '459', name: 'Madhabpur' },
      { id: '460', name: 'Nabiganj' },
      { id: '461', name: 'Shaistagonj' },
    ],
    '52': [
      { id: '462', name: 'Moulvibazar Sadar' },
      { id: '463', name: 'Barlekha' },
      { id: '464', name: 'Juri' },
      { id: '465', name: 'Kamalganj' },
      { id: '466', name: 'Kulaura' },
      { id: '467', name: 'Rajnagar' },
      { id: '468', name: 'Sreemangal' },
    ],
    '53': [
      { id: '469', name: 'Bishwamvarpur' },
      { id: '470', name: 'Chhatak' },
      { id: '471', name: 'Derai' },
      { id: '472', name: 'Dharampasha' },
      { id: '473', name: 'Dowarabazar' },
      { id: '474', name: 'Jagannathpur' },
      { id: '475', name: 'Jamalganj' },
      { id: '476', name: 'Sulla' },
      { id: '477', name: 'Sunamganj Sadar' },
      { id: '478', name: 'Shanthiganj' },
      { id: '479', name: 'Tahirpur' },
      { id: '494', name: 'Modhyanagar' },
    ],
    '54': [
      { id: '480', name: 'Sylhet Sadar' },
      { id: '481', name: 'Beanibazar' },
      { id: '482', name: 'Bishwanath' },
      { id: '483', name: 'Dakshin Surma' },
      { id: '484', name: 'Balaganj' },
      { id: '485', name: 'Companiganj' },
      { id: '486', name: 'Fenchuganj' },
      { id: '487', name: 'Golapganj' },
      { id: '488', name: 'Gowainghat' },
      { id: '489', name: 'Jointapur' },
      { id: '490', name: 'Kanaighat' },
      { id: '491', name: 'Zakiganj' },
      { id: '492', name: 'Nobigonj' },
    ],
    '55': [
      { id: '270', name: 'Bagerhat Sadar' },
      { id: '271', name: 'Chitalmari' },
      { id: '272', name: 'Fakirhat' },
      { id: '273', name: 'Kachua' },
      { id: '274', name: 'Mollahat' },
      { id: '275', name: 'Mongla' },
      { id: '276', name: 'Morrelganj' },
      { id: '277', name: 'Rampal' },
      { id: '278', name: 'Sarankhola' },
    ],
    '56': [
      { id: '279', name: 'Damurhuda' },
      { id: '280', name: 'Chuadanga-S' },
      { id: '281', name: 'Jibannagar' },
      { id: '282', name: 'Alamdanga' },
    ],
    '57': [
      { id: '283', name: 'Abhaynagar' },
      { id: '284', name: 'Keshabpur' },
      { id: '285', name: 'Bagherpara' },
      { id: '286', name: 'Jessore Sadar' },
      { id: '287', name: 'Chaugachha' },
      { id: '288', name: 'Manirampur' },
      { id: '289', name: 'Jhikargachha' },
      { id: '290', name: 'Sharsha' },
    ],
    '58': [
      { id: '291', name: 'Jhenaidah Sadar' },
      { id: '292', name: 'Maheshpur' },
      { id: '293', name: 'Kaliganj' },
      { id: '294', name: 'Kotchandpur' },
      { id: '295', name: 'Shailkupa' },
      { id: '296', name: 'Harinakunda' },
    ],
    '59': [
      { id: '297', name: 'Terokhada' },
      { id: '298', name: 'Batiaghata' },
      { id: '299', name: 'Dacope' },
      { id: '300', name: 'Dumuria' },
      { id: '301', name: 'Dighalia' },
      { id: '302', name: 'Koyra' },
      { id: '303', name: 'Paikgachha' },
      { id: '304', name: 'Phultala' },
      { id: '305', name: 'Rupsa' },
    ],
    '60': [
      { id: '306', name: 'Kushtia Sadar' },
      { id: '307', name: 'Kumarkhali' },
      { id: '308', name: 'Daulatpur' },
      { id: '309', name: 'Mirpur' },
      { id: '310', name: 'Bheramara' },
      { id: '311', name: 'Khoksa' },
    ],
    '61': [
      { id: '312', name: 'Magura Sadar' },
      { id: '313', name: 'Mohammadpur' },
      { id: '314', name: 'Shalikha' },
      { id: '315', name: 'Sreepur' },
    ],
    '62': [
      { id: '316', name: 'angni' },
      { id: '317', name: 'Mujib Nagar' },
      { id: '318', name: 'Meherpur-S' },
    ],
    '63': [
      { id: '319', name: 'Narail-S Upazilla' },
      { id: '320', name: 'Lohagara Upazilla' },
      { id: '321', name: 'Kalia Upazilla' },
    ],
    '64': [
      { id: '322', name: 'Satkhira Sadar' },
      { id: '323', name: 'Assasuni' },
      { id: '324', name: 'Debhata' },
      { id: '325', name: 'Tala' },
      { id: '326', name: 'Kalaroa' },
      { id: '327', name: 'Kaliganj' },
      { id: '328', name: 'Shyamnagar' },
    ],
  };